name: Sync fork
on:
  schedule:
    # 20分に1回実行するようにスケジュールする
    - cron: '*/20 * * * *'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch upstream
      run: |
        git config --global user.name ${{ secrets.NAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git remote add upstream https://github.com/yassun-youtube/the-hack-2022-nov-team-6.git
        git fetch upstream

    - name: Check differences and Run
      run: |
        DIFF=$(git diff HEAD upstream/mains)
        if [ -z "$DIFF" ]; then
          echo "No differences found."
          git push --force-with-lease
          curl -X POST --data-urlencode "payload={\"channel\": \"#チーム開発_チーム6\", \"username\": \"webhookbot\", \"text\": \" Deployed to vercel. Check https://the-hack-2022-nov-team-6.vercel.app \"}" ${{ secrets.WEBHOOK_URL }}
          exit 0
        else
          echo "Differences found. Updating fork..."
        fi
