name: Merge upstream branches
on:
  # Runs on 10 minutes past every hour（毎 n 時 10 分に実行）
  schedule:
    - cron:  '10 */1 * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        env:
          REPO_FORK: https://github.com/yassun-youtube/the-hack-2022-nov-team-6.git
        run: |
          git config --global user.name ${{ secrets.NAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          
          # git rebase をデフォルトに設定
          git config --global pull.rebase merges

          # 過去のコミットが取得されないと、コミット歴に不統合が発生した旨のエラーが発生。
          git pull --unshallow

          # フォーク元のリポジトリをリモート先として "upstream" に変更
          git remote add upstream ${REPO_FORK}
          
          # upstream のブランチをローカルに取得
          git fetch upstream
          
          # master ブランチの変更をマージし、clone 元の master に push
          git checkout main
          git merge --no-edit upstream/main
          git push origin main

          curl -X POST --data-urlencode "payload={\"channel\": \"#チーム開発_チーム6\", \"username\": \"webhookbot\", \"text\": \" Deployed to vercel. Check https://the-hack-2022-nov-team-6.vercel.app \"}" ${{ secrets.WEBHOOK_URL }}